arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.050000000000000003
  kinematics_solver_timeout: 0.050000000000000003
hand:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.050000000000000003
  kinematics_solver_timeout: 0.050000000000000003