# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - agrobot_joint1
      - agrobot_joint2
      - agrobot_joint3
      - agrobot_joint4
      - agrobot_joint5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity