slam_toolbox:
  ros__parameters:

    # 插件参数
    solver_plugin: solver_plugins::CeresSolver  # 使用CeresSolver作为求解器插件。CeresSolver是一种强大的非线性优化工具，广泛用于SLAM和视觉SLAM中，用于提高位姿估计的精度。
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY  # 选择稀疏的Normal-Cholesky方法作为线性求解器，适用于处理稀疏矩阵，计算效率高。
    ceres_preconditioner: SCHUR_JACOBI  # 使用Schur-Jacobi预条件器，有助于加速迭代求解过程，特别是在处理大规模问题时。
    ceres_trust_strategy: LEVENBERG_MARQUARDT  # 选择Levenberg-Marquardt作为信赖域策略，这是一种结合了梯度下降和牛顿法的混合优化算法，适合解决非线性最小二乘问题。
    ceres_dogleg_type: TRADITIONAL_DOGLEG  # 采用传统Dogleg方法进行优化，它在全局搜索和局部搜索之间取得平衡。
    ceres_loss_function: None  # 不使用额外的损失函数，意味着直接使用误差进行优化计算。

    # ROS参数
    odom_frame: odom  # 里程计坐标系的名称，用于表示机器人在局部坐标系中的位置和姿态。
    map_frame: map  # 地图坐标系的名称，表示机器人在全局环境中的位置，用于SLAM构建地图。
    base_frame: base_footprint  # 机器人基座的坐标系，通常用于表示机器人的底盘位置，是其他坐标系的参考点。
    scan_topic: /scan  # 激光扫描话题的名称，SLAM工具箱将从该话题接收激光雷达数据以构建地图和进行定位。
    mode: localization  # 设置为localization模式以执行定位任务。设置为mapping则用于建图。

    # 如果希望在启动时立即从某个位置开始定位或继续建图
    map_file_name: '/root/ros2_projects/simulation_agrobot_ws/src/agrobot_mapping/maps/small_house'  # 地图文件的路径和名称，提供此文件将从该地图开始定位。
    map_start_pose: [1.0, 1.0, 0.0]  # 地图中的起始位姿，表示机器人在地图中的初始位置，格式为[x, y, theta]。

    debug_logging: false  # 是否启用调试日志输出，false表示关闭调试日志，减少不必要的输出。
    throttle_scans: 1  # 控制激光扫描数据处理的频率，1表示处理所有扫描数据，增大该值可以减少处理频率。
    transform_publish_period: 0.02  # 里程计变换的发布周期（秒），较小的值会增加TF变换的发布频率，0表示不发布变换。
    map_update_interval: 1.0  # 地图更新的时间间隔（秒），设置为5秒以减少频繁更新带来的计算负担。
    resolution: 0.05  # 地图的分辨率（米/像素），较小的值表示更高的分辨率，可以生成更精细的地图，但计算量更大。
    min_laser_range: 0.0  # 激光雷达的最小测量范围（米），低于此距离的测量数据将被忽略，过滤掉近距离噪声。
    max_laser_range: 20.0  # 激光雷达的最大测量范围（米），超过此距离的测量数据将被忽略，避免使用无效数据。
    minimum_time_interval: 0.5  # 激光扫描数据的最小时间间隔（秒），用于减少过于频繁的数据处理，降低系统负载。
    transform_timeout: 0.2  # 变换的超时时间（秒），超过此时间未获取到变换将视为超时，处理系统延迟问题。
    tf_buffer_duration: 30.0  # TF变换缓存的持续时间（秒），确保有足够的历史数据供查询。
    stack_size_to_use: 40000000  # 程序所需的堆栈大小（字节），在处理大规模地图时需要较大的堆栈空间以避免内存溢出。

    # 通用参数
    use_scan_matching: true  # 是否启用扫描匹配功能，启用后可以提高地图构建和定位的精度，特别是在特征稀少的环境中。
    use_scan_barycenter: true  # 是否使用扫描的重心进行匹配，启用后可以增加匹配的稳定性和准确性。
    minimum_travel_distance: 0.001  # 机器人必须移动的最小距离（米），超过此距离才会更新地图，避免不必要的更新。
    minimum_travel_heading: 0.001  # 机器人必须转动的最小角度（弧度），超过此角度才会更新地图，避免频繁更新。
    scan_buffer_size: 3  # 扫描数据缓冲区的大小，用于存储最近的激光扫描数据，以便进行匹配和分析。
    scan_buffer_maximum_scan_distance: 10.0  # 扫描缓冲区内允许的最大扫描距离（米），超过此距离的数据将被丢弃。
    link_match_minimum_response_fine: 0.1  # 细粒度匹配的最小响应值，低于此值的匹配将被忽略，视为不可靠。
    link_scan_maximum_distance: 1.5  # 链接扫描的最大距离（米），用于确定哪些扫描结果可以作为有效的匹配依据。
    do_loop_closing: true  # 是否启用回环闭合功能，启用后可以减少累积误差，防止地图因漂移而失真。
    loop_match_minimum_chain_size: 3  # 回环匹配的最小链条大小，较小的值可以更早地检测到回环，但可能引入误匹配。
    loop_match_maximum_variance_coarse: 3.0  # 粗粒度回环匹配的最大方差，控制匹配的容忍度，防止错误匹配。
    loop_match_minimum_response_coarse: 0.35  # 粗粒度回环匹配的最小响应值，低于此值的匹配结果将被过滤掉。
    loop_match_minimum_response_fine: 0.45  # 细粒度回环匹配的最小响应值，用于提高匹配精度和回环检测的可靠性。

    # 相关参数
    correlation_search_space_dimension: 0.5  # 相关搜索空间的维度（米），定义搜索空间的大小，用于优化计算。
    correlation_search_space_resolution: 0.01  # 相关搜索空间的分辨率（米），分辨率越高，匹配精度越高，但计算量也更大。
    correlation_search_space_smear_deviation: 0.1  # 相关搜索空间的偏差（米），用于处理噪声和不确定性，增加匹配的鲁棒性。

    # 回环闭合参数
    loop_search_space_dimension: 8.0  # 回环搜索空间的维度（米），定义回环检测的搜索范围，决定回环闭合的检测能力。
    loop_search_space_resolution: 0.05  # 回环搜索空间的分辨率（米），较高的分辨率可以提高回环检测的精度。
    loop_search_space_smear_deviation: 0.03  # 回环搜索空间的偏差（米），用于处理噪声和不确定性，增加回环检测的鲁棒性。

    # 扫描匹配参数
    distance_variance_penalty: 0.5  # 距离方差惩罚系数，用于限制距离误差的影响，减少错误匹配的可能性。
    angle_variance_penalty: 1.0  # 角度方差惩罚系数，用于限制角度误差的影响，确保匹配角度的精度。
    fine_search_angle_offset: 0.00349  # 细粒度搜索的角度偏移（弧度），用于提高匹配的精度。
    coarse_search_angle_offset: 0.349  # 粗粒度搜索的角度偏移（弧度），用于快速初步匹配，但可能影响精度。
    coarse_angle_resolution: 0.0349  # 粗粒度角度搜索的分辨率（弧度），较低的分辨率可以提高搜索速度，但可能降低精度。
    minimum_angle_penalty: 0.9  # 最小角度惩罚系数，用于避免过大的角度误差，确保匹配的角度精度。
    minimum_distance_penalty: 0.5  # 最小距离惩罚系数，用于避免过大的距离误差，确保匹配的空间精度。
    use_response_expansion: true  # 是否使用响应扩展，启用后可以提高匹配的鲁棒性，减少局部最优解的影响。
